version: "3"

networks:
  traefik-proxy-network:
    external: true
    name: ${TRAEFIK_NETWORK}
  backend:
    driver: bridge

services:
  ### RabbitMQ
  rabbitmq:
    environment:
      - DOMAIN
      - RABBITMQ_IMAGE
      - RABBITMQ_VER
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - TRAEFIK_CERTRESOLVER
      - TRAEFIK_ENABLE
      - TRAEFIK_ENTRYPOINT
      - TRAEFIK_MIDDLEWARES
      - TRAEFIK_NETWORK
      - TRAEFIK_ROUTER
      - TRAEFIK_TLS_ENABLE
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE}"
      - "traefik.docker.network=${TRAEFIK_NETWORK}"
      - "traefik.http.routers.${TRAEFIK_ROUTER}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${TRAEFIK_ROUTER}.entrypoints=${TRAEFIK_ENTRYPOINT}"
      - "traefik.http.routers.${TRAEFIK_ROUTER}.service=${TRAEFIK_ROUTER}"
      - "traefik.http.services.${TRAEFIK_ROUTER}.loadbalancer.server.port=${TRAEFIK_PORT}"
      - "traefik.http.routers.${TRAEFIK_ROUTER}.tls=${TRAEFIK_TLS_ENABLE}"
      - "traefik.http.routers.${TRAEFIK_ROUTER}.tls.certresolver=${TRAEFIK_CERTRESOLVER}"
      - "traefik.http.routers.redirects.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${TRAEFIK_ROUTER}.middlewares=${TRAEFIK_MIDDLEWARES}"

    networks:
      - traefik-proxy-network
      - backend
    build:
      context: ./docker/rabbitmq
      args:
        # This is needed for passing environment variables to the docker build contect.
        - "RABBITMQ_VER=${RABBITMQ_VER}"
        - "RABBITMQ_IMAGE=${RABBITMQ_IMAGE}"
    restart: always
