# Capture environment variables from passed arguments and setup default value.
ARG RABBITMQ_VER=${RABBITMQ_VER}
ARG RABBITMQ_IMAGE=${RABBITMQ_IMAGE}

# Image and version to pull
FROM ${RABBITMQ_IMAGE}:${RABBITMQ_VER}
